name: CD

on:
  push:
    branches:
      - main

jobs:
  # ==========================================
  # JOB 1: VERSIONING & RELEASE
  # ==========================================
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Used to create tags and releases on GitHub
      issues: write # Used to comment resolved issues
      pull-requests: write # Used to comment pull requests
    outputs:
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necessary to analyze commit history

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        env:
          # GITHUB_TOKEN is automatically given through GitHub Actions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}